def physics_menu():
    print("-------------------------------------------------------------")
    print("----------Welcome to the Styfer AI Physics Toolkit-----------")
    print("-------------------------------------------------------------")
    print("1 - Speed / Distance / Time")
    print("2 - Velocity / Displacement / Time")
    print("3 - Acceleration / Velocity / Time")
    print("4 - Force / Mass / Acceleration")
    print("5 - Momentum / Mass / Velocity")
    print("6 - Impulse / Force / Time")
    print("7 - Torque / Force / Radius ")
    print("8 - Work Done / Force / Displacement")
    print("9 - Potential Energy / Mass / Height")
    print("10 - Kinetic Energy / Mass / Velocity")
    print("11 - Exit")
