def utilities_menu():
    print("-------------------------------------------------------------")
    print("----------Welcome to the Styfer AI Utilities Manager---------")
    print("-------------------------------------------------------------")
    print("1 - Calculator")
    print("2 - Physics Toolkit")
    print("3 - Unit Conversion")
    print("4 - Currency Converter")
    print("5 - Other Tools")
    print("6 - Exit")
